# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sennin
email: rui@sennin.pt
description: > # this means to ignore newlines until "baseurl:"
  Rui's blog.
  
cover: /assets/blog-cover.png
logo: /assets/small-logo.png
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ruipires
github_username:  ruipires
permalink: /:year/:month/:day/:title
# permalink: /:title
#permalink: /author/:author
paginate: 10

collections:
  projects:
    output: true


# Build settings
markdown: kramdown
highlighter: rouge
#theme: jasper2
remote_theme: ruipires/jekyll-theme-geist

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - README.md
  - Vagrantfile
  - Rakefile
#plugins_dir:
#  - jekyll-paginate
#  - _plugins

# jasper2 settings
navigation: True
twitter: ruipires
github: ruipires 

google_analytics: UA-30944614-1
google_site_verification: 95_d8hcENZX0UvvX8v7F7ExMr4iCEjQzsBcqNMsdyDo

plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml
